### ISSUE TITLE
Should we use exact three capital letters for all constructions?

### ISSUE THREAD

**Issue by cybcatppuccino** [jjdishere/EG#49]
Example 
PNT : point
LIN : line
SEG : segment
SGN : segment nondegenerate
ANG : angle (itself, the oriented angle, value is not a construction)
TRI : triangle
ARC : arc
SQR : square
QDR : quadrilateral
INX : intersection (this is an intersection)

**Comment by jjdishere** [comment]
I support

**Comment by cybcatppuccino** [comment]
This makes the files we are going to write some how more beautiful.

**Comment by Liang-Xiao-pku** [comment]
Nice idea. Will change to this convention.

**Comment by Liang-Xiao-pku** [comment]
SGN 可能不太行 sign，建议SGP (sgp) for segment of positive length
QDR or QDL 我们再讨论一下qdr qdl

**Comment by jjdishere** [comment]
_nd is preserved. PNT is not being used.

**Comment by jjdishere** [comment]
TRI is added.
ARC QDR is not defined yet.
ANG : angle (itself, the oriented angle, value is not a construction) updated.


INX : We write `is_inx p l_1 l_2`. Currently no definition of `INX`
