### ISSUE TITLE
two different prove route map towards congruent

### ISSUE THREAD

**Issue by cybcatppuccino** [jjdishere/EG#51]
the key theorem to many other theorems is that SAS implies congruent 
but we have two ways proving SAS and other congruent theorems (both NOT easy)
one way to define congruent: 
1) prove Pythagoras theorem by Vector (in which file? perp?)
-- the Py theorem is a general theorem which is useful in many situations
2) prove cosine theorem (in which file?)
3) prove cos an angle determines an angle in [0, \pi] (in the file angle)
4) use 2) to prove the third edge is of same length, use 3) to prove the rest angles are of same degree (using orientation of TRI)

second way to define congruent: (the same technique Euclid used, but Euclid didn't claim congruent properly)
1) to define isometry as a transition after a rotation
2) prove theorems about things didn't change under rotations and transitions (this step requires one to unfold Vector)
3) prove that any pair of angles with same degree could be translated under an isometry (after acting isometry, we get equal source and Dir)
4) prove SAS just as Euclid did (this might be not easy too)

Now which route is better? And do we need both two routes to define congruent for general objects?

**Comment by Liang-Xiao-pku** [comment]
My thinking on this matter is: probably we need to implement both proofs anyways (as both methods are used in advanced argument in Euclidean geometry). So my current thinking is based on how to establish foundation in a good order.

I vote for implementing this in the first way: In the triangle folder, after Basic.lean, we insert a Trigonometric.lean to prove cosine and sine theorem (AB/sin C = AC / sin B). (Of course, I would love to prove the sine theorem as AB = 2R sin C). And as well as the statement about cos determines angle.

This should be enough to prove SAS AAS and SSS.

We do need some sort of rotation thing, which can be done later, and be stated as: congruent triangles can be done as rotation + translation. Once that is done, we can do more things such as incenter/orthocenter/circumcenter of congruent triangles match.  (Acutually, part 4 might not be so difficult.)

Another reason I vote for first way is: for the second way, it is a little annoying the triangle reverses orientation.

**Comment by jjdishere** [comment]
Currently, we have decided to use cosine theorem as a basis to prove SAS.
