### ISSUE TITLE
Definition of Vec can be modified to enable instances

### ISSUE THREAD

**Issue by jjdishere** [jjdishere/EG#58]
Instead of
```
notation "Vec" => \mathbb{R} * \mathbb{R}
```
we may use
```
class Vec where
   fst :  \mathbb{R}
   snd :  \mathbb{R}
```
This will enable us to use instances without messing up with product structure on  \mathbb{R} \times  \mathbb{R}

**Comment by cybcatppuccino** [comment]
This should be careful - how much would we need to fix our code if we do this?

**Comment by jjdishere** [comment]
This issue closed naturally with another issue raised. see https://github.com/jjdishere/EG/issues/78
