### ISSUE TITLE
Shall we define LinetoRay?

### ISSUE THREAD

**Issue by cybcatppuccino** [jjdishere/EG#60]
A point LiesOn a line splits the line into two rays. This is some how a version of the Archimedean property of the line. 

-- Arch property : \any r : \R, \exist s : \R such that s > r. 
-- Another note : The Arch prop section now in Line.lean and the real Arch property have different meanings.

**Comment by cybcatppuccino** [comment]
This is useful when we are going to pick points on a line "at random" but not "too random". I mean that we can pick point which "lies on the left" of some fixed point.

**Comment by cybcatppuccino** [comment]
An ray of course have a nontriv pt different from source : ray.dir +v ray.source.

**Comment by jjdishere** [comment]
I don't really understand your idea. from a point on a line you can get 2 rays, how do you distinguish them? Choose them randomly?

By the way, I don't feel guilty when I use `choose` :P

I support you that the current Arch theorem is not the same meaning of usually what we call. should rename and add theorem.

**Comment by Liang-Xiao-pku** [comment]
My thought is: let's think about what we really need in practice. If this is to make some proof more convenient, I think "choose" might be just good enough. But if we need to actually construct some ray out of the line, then maybe, we would already have a point, and maybe there is a way to get a direction...

**Comment by jjdishere** [comment]
trivial after definition of Line changed.
